# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 369c444143568d2feebde136d360424d94a36923098cfa8b9092310246d82328fdf4ac650e3fb98bc9bbefddb66c92e1d8c0a0c0d2eaf68412f00d170ae4ceaf

test:
  secret_key_base: 0a96698b3c64cb8d97bb976ac057688baf0f22f61e991eee839b289491064c6689edcedb9a4016b02a8264165f1eee40f9a48ca2905fc05de25583a5bce87fd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
